### PR TITLE
do not ship test files (especially not a full rails app) and do not s…

### PR DESCRIPTION
**Pull request by grosser**
…hip logs, also simplify gemspec a bit

was searching through my bundle gems and found the development.log in this gem ... should propably not be shipped :)
(making the gem faster to install + repos smaller when vendoring gems)

@fatdude

### CODE REVIEW

**Comment by fatdude** [comment]
Cheers. Been a real slacker with this, got a couple of other pull requests that need merging so I'll hopefully get this all sorted and released this weekend.

**Comment by grosser** [comment]
ready to go ?

**Comment by knightq** [comment]
Cool, will you merge this soon?

**Comment by grosser** [comment]
@fatdude gogogo :D

**Comment by grosser** [comment]
@fatdude merge ?

**Comment by dgilperez** [comment]
some merging here for a :beer:?

**Comment by dgilperez** [comment]
:clap:

**Comment by grosser** [comment]
I see how it works ... gotta bring bribes 🍻  ...

**Comment by dgilperez** [comment]
:tada: 

Hey, @fatdude what can I offer you for a new gem release? :tropical_drink: :cocktail:

**Comment by fatdude** [comment]
Sorry all! Been a complete slacker on this, no excuses. 

Pull requests merged and gem pushed. Thanks to all! It should be me buying the beers.

**Comment by dgilperez** [comment]
:tada: :beers: for all

**Pull request merged**
